# Copyright Jeron Aldaron Lau 2019-2020.
# Distributed under either the Apache License, Version 2.0
#    (See accompanying file LICENSE_APACHE_2_0.txt or copy at
#          https://apache.org/licenses/LICENSE-2.0),
# or the Boost Software License, Version 1.0.
#    (See accompanying file LICENSE_BOOST_1_0.txt or copy at
#          https://www.boost.org/LICENSE_1_0.txt)
# at your option. This file may not be copied, modified, or distributed except
# according to those terms.

[package]
name = "pasts"
version = "0.7.2"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR BSL-1.0"

description = "Minimal and simpler alternative to the futures crate."
repository = "https://github.com/AldaronLau/pasts"
documentation = "https://docs.rs/pasts"
homepage = "https://github.com/AldaronLau/pasts/blob/master/CHANGELOG.md"
include = ["Cargo.toml", "README.md", "src/*"]
keywords = ["futures", "platform-agnostic", "cross-platform", "io", "executor"]
categories = ["asynchronous", "embedded", "no-std", "rust-patterns", "wasm"]
readme = "README.md"
edition = "2018"

[dependencies]

[build-dependencies]

[dev-dependencies]
async-std = "1.0"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[features]
default = ["std"]
std = []
